site_name: Easton
dev_addr: 0.0.0.0:8000
docs_dir: docs
copyright: Copyright © 2025 All Rights Reserved # - <a href="#__consent">Change cookie settings</a>         # 版权声明

repo_url: https://github.com/iseastonlee      # git仓库地址
repo_name: Easton                             # 仓库名称

theme:
  name: material
  language: zh
  custom_dir: overrides
  favicon: images/avatar/spider-man.svg       # 网站图标

  font:
    text: Chiron Sung HK

  icon:
    logo: other/spiderman                     # Logo 图标
    repo: fontawesome/brands/github           # 仓库图标
  
  palette:
    - media: "(prefers-color-scheme)"         # 自动模式
      toggle:
        icon: material/link
        name: 自动亮/暗
    
    - media: "(prefers-color-scheme: light)"  # 日间模式
      scheme: default                         # default / slate
      primary: white                          # 导航栏背景色
      toggle:
        icon: material/toggle-switch
        name: 日间模式

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"   # 夜间模式
      scheme: slate
      primary: black                          # 导航栏背景色
      toggle:
        icon: material/toggle-switch-off-outline
        name: 夜间模式

  features:
    - navigation.top                          # 返回顶部的按钮
    - navigation.tabs                         # 导航栏
    - navigation.tracking                     # 锚跟踪
    - navigation.instant                      # 即时加载
    - navigation.instant.prefetch             # 即时预取
    - navigation.instant.progress             # 进度指标
    # - navigation.tabs.sticky                  # 导航栏始终显示
    - navigation.sections                     # 不折叠导航栏
    - navigation.indexes                      # 排除 Blog 标题 在页面导航栏重复问题
    # - navigation.path                         # 显示当前路径
    - search.highlight                        # 高亮显示搜索内容
    - search.suggest                          # 搜索建议
    - search.share                            # 搜索共享
    - content.code.select                     # 代码选择按钮
    - content.code.copy                       # 代码复制按钮
    - content.code.annotate                   # 代码注释
    - content.tabs.link                       # 链接内容选项卡
    - content.tooltips                        # 替换浏览器的 title 属性渲染逻辑
    - content.footnote.tooltips               # 注脚工具提示

extra:
  generator: false                            # 关闭 MKDOCS 来源页脚
  social:
    - icon: material/folder
      link: /public/
      name: Public
    - icon: material/folder-lock
      link: /private/
      name: Private
    - icon: simple/openwrt
      link: http://10.0.0.1
      name: Openwrt
    - icon: material/speedometer
      link: http://10.0.0.1:3300
      name: Speedtest
    - icon: material/router-network-wireless
      link: http://10.0.0.1:16601
      name: Lucky
    - icon: material/minecraft
      link: http://10.0.0.109:23333
      name: Minecraft
    - icon: material/google-translate
      link: https://translate.google.com/?hl=zh-CN&sl=zh-CN&tl=en&op=translate
      name: Translate
  # consent:
  #   title: 🍪 Cookie 偏好许可
  #   description: >- 
  #     我会使用 Cookie 来识别您的重复访问和偏好，以及衡量文档的有效性以及您是否找到了正在搜索的内容。获得您的同意，您将帮助我们改进我们的文档。

#-----------------------------
# 引入插件
#-----------------------------
plugins:
  - search                                    # 搜索功能
  - blog:
      archive_date_format: yyyy               # 归档时间格式
      blog_toc: true                          # 在 Blog 主页中显示文章目录
      post_date_format: short                 # 日期格式 yyyy mm dd week
      post_excerpt: optional                  # 摘录，optional选择写，required必写
      post_excerpt_separator: <!-- more -->   # 生成摘录，more 以上为摘录
  - glightbox:                                # 图片放大功能
      draggable: true                         # 图片可拖动
      touchNavigation: true                   # 触摸触摸导航(滑动)
      loop: true                              # 图片循环  
  - tags                                      # 标签
  - privacy

#-----------------------------
# 引入 css 文件
#-----------------------------
extra_css:
  - stylesheets/extra.css
  - stylesheets/index.css

#-----------------------------
# 引入 js 文件
#-----------------------------
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
  - javascripts/index.js

#-----------------------------
# Python Markdown 扩展
#-----------------------------
markdown_extensions:
  # Python Markdown 内置扩展
  - abbr                                      # 缩写，比如HTML写成[*HTML]: HyperText Markup Language
  - admonition                                # 提示框，比如!!! note "标题"
  - attr_list                                 # 允许在元素后添加{: .class #id}这样的属性
  - def_list                                  # 定义列表，允许使用术语和定义的写法，类似<dl>的效果。
  - footnotes                                 # 脚注，用[^1]标记脚注，然后在文末写[^1]: 内容
  - md_in_html                                # md_in_html：在HTML块中允许使用markdown语法
  - toc:                                      # 自动生成目录
      # permalink: true                         # 在标题旁显示永久链接符号

  # PyMdown 扩展（需安装 pymdown-extensions）
  - pymdownx.arithmatex:                      # LaTeX 数学公式支持
      generic: true                           # 使用通用数学解析器
  - pymdownx.betterem:                        # 更智能的强调语法
      smart_enable: all                       # 同时启用 _ 和 * 的智能强调
  - pymdownx.caret                            # 支持上标和插入符（例：^上标^）
  - pymdownx.details                          # 折叠内容区块（类似 <details>）
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji      # 使用 Twemoji 图标集
      emoji_generator: !!python/name:material.extensions.emoji.to_svg   # 生成 SVG 格式
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:                       # 增强代码高亮（替代默认高亮）
      anchor_linenums: true
      linenums: true
  - pymdownx.keys                             # 键盘按键样式（例：++ctrl+c++）
  - pymdownx.mark                             # 文本标记支持（==高亮文本==）
  - pymdownx.smartsymbols                     # 智能符号转换（例：(c) → ©）
  - pymdownx.superfences:                     # 嵌套代码块支持（解决列表中的代码块问题）
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:                          # 选项卡式内容区块
      alternate_style: true                   # 使用替代样式主题
  - pymdownx.tasklist:                        # 任务列表支持
      custom_checkbox: true                   # 自定义复选框样式
  - pymdownx.tilde                            # 删除线扩展（支持 ~~删除线~~）
  - pymdownx.blocks.caption

nav:
- Home: index.md
- Tools: tools.md
- Recom: 
  - recom/recom.md
  - Clash Verge Rev: recom/ClashVergeRev.md
  - Clash Meta: recom/ClashMeta.md
  - gh-proxy: recom/gh-proxy.md
# - Movie: movie.md
- Blog:
  - blog/index.md
  - Important:
    - 妙妙小命令: blog/posts/OS/妙妙小命令.md
- About: about.md
# - Test: test.md