name: Lee 
on:
  push:
    branches:
      - master 
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Commit and push compiled site to public repository
        run: |
          cd public-repo
          git config user.name "LeeYearn"
          git config user.email "leeyearn@gmail.com"
          git add .
          git commit -m "Sync compiled site from private repository" || echo "No changes to commit"
          git push
      
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 

      - name: Checkout public repository
        uses: actions/checkout@v4
        with:
          repository: liycn/liycn.github.io
          token: ${{ secrets.PUBLIC_REPO_TOKEN }}
          path: public-repo

      - name: Debug: Check directories
        run: ls -al


      - run: pip install \
                mkdocs-material \
                mkdocs-glightbox \
                pymdown-extensions \
                "mkdocs-material[imaging]"

      - run: mkdocs build  # 生成 site/ 目录

      - name: Upload site directory
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: site/  # 上传 site/ 目录

  sync:
    runs-on: ubuntu-latest
    needs: deploy  # 确保 deploy 任务先执行
    steps:
      - name: Checkout public repository
        uses: actions/checkout@v4
        with:
          repository: liycn/liycn.github.io  # 你的目标公共仓库
          token: ${{ secrets.PUBLIC_REPO_TOKEN }}
          path: public-repo

      - name: Download site artifact
        uses: actions/download-artifact@v4
        with:
          name: site
          path: site/  # 下载到 site/

      - name: Clear old files in public repository
        run: |
          rm -rf public-repo/*

      - name: Copy compiled site to public repository
        run: |
          cp -r site/* public-repo/

      - name: Commit and push compiled site to public repository
        run: |
          cd public-repo
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "Sync compiled site from private repository" || echo "No changes to commit"
          git push
